version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    ports: 
     - "5680:5672"  
  flask-app:
    build:
      context: web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5112:5000"
    depends_on:
     - rabbit
  mail-sender:
    build:
      context: mail_accept
      dockerfile: Dockerfile
    restart: always
    depends_on:
     - rabbit
